apiVersion: v1
kind: ConfigMap
metadata:
  name: llm-evaluation-service-config
  namespace: llm-evaluation
data:
  APP_ENVIRONMENT: "portfolio"
  APP_LOG_LEVEL: "INFO"
  APP_OTEL_ENABLED: "true"
  APP_OTEL_EXPORTER: "otlp"
  APP_OTEL_OTLP_ENDPOINT: "http://otel-collector:4317"
  APP_STORAGE_BACKEND: "postgres"
